# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160322152221 on 2016-04-07 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_choice_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='ans',
            field=models.BooleanField(),
        ),
    ]
