# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160322152221 on 2016-04-07 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20160407_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
