# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160322152221 on 2016-04-08 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_auto_20160407_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='ans',
            field=models.BooleanField(default=False),
        ),
    ]
