# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160322152221 on 2016-04-26 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0006_auto_20160423_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choicegramm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('ans', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Quesgramm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, unique=True)),
                ('group', models.CharField(max_length=200)),
            ],
        ),
    ]
