# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160322152221 on 2016-04-26 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0008_auto_20160426_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicegramm',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.Questiongramm'),
        ),
    ]
